language: node_js
sudo: true
if: tag IS blank
cache:
  directories:
  - ".npm"
  - "~/.npm"
  - node_modules
  - "/home/travis/.cypress/Cypress"
addons:
  apt:
    packages:
    - bsdtar
    - build-essential
    - make
  #chrome: stable
env:
  global:
  - USER="4dn-dcic"
  - FOURFRONT_BRANCH="selenium"
  - secure: fJT/nDt68Av0IsbwDk9z/qk36uwv81Y27u81I4MaeAMUsMiQMSXd2NaBmvqD+/utf0toAxi7f0vadHchG2dGfR0ZlbVVMTx9xeG7ahMILHH2m/g9k2yI2HnFl2eBryckfnGwtLuLDxYCY2qwkSP6WCw4Hy3yNVd5zWUMabf7/t92IoMezjbdwn/iwQqzyvU6PESgiWjAjuAHjsQQHWIJoIpsB9PM+R1uRIdIf7dV6tytKd5cCUloHJolniJpJtQM4jsTOBlWWaYlzDbRivIhmxqSwL+mBG8VsBkk9f8AFRdvJ3d6M+Kp67IxQ8Cyy+Efavs3K7Lc0eZD98tWz0Hta++Cm5C5dCKcgSZMF4ift+dEkXei/YUTO3ruBV/Ogd7Nxv6vLoFmL5v+FsVj3+TTnUvjwKcPjF81rRP7tldi+AXipG7M7CVKUdPbTuQY+hMZM/i7RgDsAWCFKwgOvKECYLeGFhE+1YPgKXVcuOkf0y++k/HB0rP8pD/94cyA5dUW85vNXh/c0iSF3m77X2D16RZCi3UaCX5okrInNn/MzPzirRNkVAGsmUgFgJvi97mlAUkzMyWhsx+1+bJlMSmN/+AZ/u613SVHuV19xdFa38zsQ/xfegZQuueoBOFd5amEghjkRTYIbPLJ/IeOvRM0ayekjQAtEdP3Na5Hw2sxj5Q=
  - secure: ES6kTjktJy60LkwMGBhMs5ueoF+v7txcTIE5UmcED9Jg2KjVDgMoEsKYPk6jaUCFrwe3KAdReAyUBN+o0oOAQN03wkoTHiUKcK6dSSgtE8Z3GXERyDHdf4AJHgj7fRl59QBmLBwc0b+21zJofb9t1va31bm8baulcxsbWqkzulWtqyBuFtoa6GAwXcP7XzZE45zoMfQPtH2HvESC67cXxOQFnNSCx040HaK5qqvBYkRIN7Ee8skrN+ZK0gurb3zpZz9DURlQ4O7OoGi5QN1ejXAbSKWj0L8luPT31S8cFlb7yZYYQIlnSwpJP760V0MrQ2ZmbGJ0n5SIUpOdjilyPsNFW3eNFf42g4KcV5stg8GQ5hg7Dv3RuH4cpYM6dS1rrDOk05wE/BF2hlSLf8X8RGGFTLyX8cpWaNvL9KK/qDYqzbzVjCitsC+KEL9xIOSD6bf7R5xPCz55eyVp4YbkP+xtAHFMIUku+D1kfIBajwiSlHioowOVMaJ9J8rT6y4liVNMT8LSZHwB1soNnceIUbO97gfh7vONwYNc+LhIU132ftsqoM1Utj1wp21yEIGUZUAmvglbv5m7IYUB5XEyV6WSHSHAICrDgOG6Lbv1DuT6oeGavqfjFx+LklXPDR55Ye/n7KPsfjUZJxp2uw6WjGuLPJVuNVP0kwKx6koqvTk=
  - secure: f33pvCgWPnoeX6BT6iJbJ8rIucz89Z5UImhqpL8Np1O9QbZduYiZ7wWzX9HfIXlD8Rq4kAHb1Yiwh7RmVJH6AFXiimjBLWP6Rr/XBvuChB3bLfIvurlVppDAa4vZ8jzO9gezZ+9GnWaRq1TcAGnvymtZW78f/DiWhOzeslXUfmkwTshZ+SgHtia8Ml3B7sKSLIFxXQ/ZOYMzvrF7w5FqFmSi5Mp+vKLnXIEa0LuLx+Vh+Q4kXzr2pkWejwMPzCOeXQ1bnddCpME2Qa5D4tW8PkK/iikPRn+WN7+VHAn10Za32wFH3cfCYFIq6wkSgTF6sPAJLy1u2l+Zj/E8F2LLmexHufGCkDskFaYbem6IKfA6ELZfQHgdGiDU4oD9175JNvHPUjzJHt3+EgEgmke+NOjAn31Qb1uD1fHemH2l/kCGKyz48d89biIhw1v7oCuojGgohEqA2tMvsaIpIrMBlez+yQrt2RzWE4Qazpbc15a54I5vGWYcvmO95ybdGj4DJDun4a46QEDmb5YkbSEiiCUwNnTjfZggm1yL3MfdAFBfA3kqaUt0jbv09secRl8ILkkNX1Ld7u1T0n69dBpgHHiGIO7g8aSToe6V3Zr7ZEA8LY4uAReV7ARGn5p4NN7Sl2lWuHZ/G/d328/eS7We4oYx+hw0JHJOjWfGp32N+1o=
#notifications:
#  slack:
#    secure: DQyUTk6evwPpO0P5+OPhBSgl+fGEerOjBlBwQliXAkDaMKH3Cpi4cTQ3ETR/+3g6bGqPGK+QJ1R+6Ht+hJD7dNomyVIoQmvF0P5afJtpk/A3cDILe90t76ET9jc/iBjWeUFQdokFUJ7Gt1GGYtI6e5XcVu/Qc/xqCvFMtsBN6mnBFuvcQki+WkoIIPPawyhfryCNOLo5vvbi4SZ5dZI+M0MGq9HQjOyF1sdIgKuXhxjupmL+kVPVXAq9kiOANYFkwbNsP9j0BTYW5wFHpAztBqz3NT6EchgCdue8tgV4hC4rRFvM/bsA4qz/TJ5wRRLBRXtnNtPcyhAqTiU+wC6qWt++fjSEMGe4KYqtRRV1YuxQiTVHN84t77DILLNfMh/6uSs0KijwOT+Oazwd/UsN1zYOH93AM4FZ0h92yyb6j6JQ+DUk4WFel1Zr4kZzhtHSPGw+K4fxY0zIt1qpaDPXjtZHQ0+LwIIMtwMp5bBcwDn9d1ADnUhUAuuIN2hHaXrVy4vP2hIcd0LzezBqvc7JXimyd5yRgUeOCTrKGkAeSo8VA7XIj0ZmlpQRYKNTJP+gz4Y6C/RCxISnFDF/vcX+IsDdvreZXJMplE1Aqxf0uR6Zj8Sr8q+QWGKydv6ettlLZuqDuv0l/l/9qpzYfRqLSZcetGRVFHHcR9wuQiDyums=
before_install:
- nvm install 8
- node --version
- npm --version
- npm config set python /usr/bin/python2.7
install:
- npm install
- git clone https://github.com/4dn-dcic/fourfront.git ./fourfront
- |
  if [ $FOURFRONT_BRANCH != "master" ]; then
    cd ./fourfront
    git fetch origin $FOURFRONT_BRANCH
    git checkout $FOURFRONT_BRANCH
    echo "Checked out branch $FOURFRONT_BRANCH" 
    cd ..
  fi
script:
- |
  travis_wait 20 $(npm bin)/cypress run --record --key $CYPRESS_KEY \
  --project ./fourfront/deploy/post_deploy_testing \
  --env Auth0Client=$Auth0Client,Auth0Secret=$Auth0Secret \
  --config baseUrl=https://data.4dnucleome.org'
after_script:
- echo $BUILD_AGGREGATE_STATUS
after_success:
- echo $TRAVIS_COMMIT_MESSAGE
- MSG_NO_WHITESPACE="$(echo -e "${TRAVIS_COMMIT_MSG}" | tr -d '[:space:]')"
- echo $MSG_NO_WHITESPACE
- echo $TRAVIS_PULL_REQUEST
- echo $TRAVIS_BRANCH
after_failure:
- export $(cat .to_export_back) >> /dev/null
#notification:
#  slack:
#    rooms:
#      secure: YuLIoKULHxT7ZY9nKVme0pVELk1HBS/nPjYYu4Bs48lOgJVK2I/OyvV9HVx2g7raK6/s4T7wTXG0EmljcakmKY78wsSyhR79fAZcV7+p4SobEi7nGHuHXVq0sp21ZeYiFJvD/5ospHX0hMudSicaANT66X7EyLTMdG/NGu5it6TPjcJWhxERXXz6Zbizm6j/wv2a64R0mMUGFSe1aWrFZv5ft+GgfupM2TPwX0PxNl2DamaGowJriKuU+svqIP7LXGuzYBxf9sj08gf3/S0e1r2bzg/ik4clzM2Lp5mcU27nLWh6TUr3hthFNsaKAFwIPS6Ay1Z8GeotAiZC538fyeM1zDvjz0Uu5fEuZnI89NVZ734NZfoFCEg4JcPDs8RHgzreR209zRgCVUh8AI7m7vMv302MNAjbG42FPlB1gDg9bukxbyytccm5/TuzAGLktG1jCWJk0uU34JsWZakF9fSqmFckppXZ1472cPQT+ityuszyUGEMgLvNxpZDpwMhywN7eMuQu64YD4ex1EvbidNEIdb0Z5UnpXaC2H+vxdBb+Qg58r/HN/S6OW8H+C/pZMuRMdm1AcgOjS9hROcRKgmwSD53Z/XXrT4GYZTW48jNOCFE2O+6RXUGqvQzcH8JG5blnTxoCV8dtb9GDbORQm7b80MOiidG8Xi8Jyq8oPM=
