language: node_js
sudo: true
if: tag IS blank
node_js:
  - 12
cache:
  npm: true
  directories:
  - "~/.cache"
addons:
  apt:
    packages:
    - libgconf-2-4
env:
  global:
  - USER="4dn-dcic"
  - secure: am2d9dEdcIFaxWTVIcO2jzg3izIpgO0gPk3Kqo4L+FV05eAoC2arse5MtcqRQ7EhaNMnbI0v4y93kyvDMwmns/ObgWYPDAsamQk/gR0g7C4YALdwOgcqlEcXOwODcOgFmJ2miWiw7YhEUTPRzCfcYx7amBz46qxv1eLvUfuktBg4eSRfRzrWaC+cndFzwxoHiRLPdVVNft33VHD01gsl7tMK3Tkv4iXcZFca+8JRBGaM2NN5PzDFbgNqi5URwLVlrHzDPUlhy2wJ8Ut5z1Vifjr5xlAWds9j0CLe0+wCjtMHpiHirpfe0pYZgRlr9j2ZfOzXRz365eDobs8hAAVSokeQJBZB7FQEzWHwX6LE2HEQUcTLSw/aqpwFlAKLIbM1GpbpGvIPzOmeEECT3vhWXjjh6oNGOm7IPwfRH5KamKnlU8VwzGl9sM1dqbVQ7gflqua8yeMcGfOfURz19rTpOl/zZfMElfmrsz9Cs1ebp9/hyADGm6E7Yc9WHWCAI2u5/Uc5XuT2hFc1Du/AtPvlxFO4zpOluQOXwCCH09upfsEGp3OykKZT38j7OGxkOFjcA30IyO3wD1HJdDMW7piz/m13EwcATsBeY9fulKVBugMcoHKcHYyu4dAyzv9Uo5+hWhguX/r2qN6QUT1CDUpLtiCpOVwIw0H5p7okRVHBG4g=
  - secure: AvtMi9wvpIKmrC/E2Ta2eIc9+uj2fI5zA5Xm6BTRVIIzDYx9Gmq1d+AIzZpi+wKdtoGb/i5JhoE62VjGSlnaSCs25/F0is67jXE6xFL8W9QkG/e6JvRAPnoTwii049WPEfPdFAdEIAxlE6ZDRIa7xGtM6lW3+WjWpkgDKkGjK/voz5/9RhJ6Hjz7u2F0tQEudshq+cQZ3JHmy1saphEX345y+2l6kFJI/2ppzIAeib65f7TZm1tmHLgzo0n0EyVAIeqhN1dhMacjRuP+ttDf1qFbuo5votJTZS17Ucq6FUu5ZUtRt3cvw6m97wsXtTQX8Nf0+++xloU4tbM96ojyMU9lH14zQZckNFIaVt0fpz3NHwELiwJw/35Jt87ql5NK3VRCfTdGcu8HLcp256Eh6+y6DcVLnpQmMVza/zInHEzzqVlATTaUNJP1Ps5Wv3ijG0caYmPUUadoTm49EqvibVepNpwusB6RkiE2OFjL1Adt5AAVCTluHea/isQUnMUg96dCvA6fE5Y9By7ZFf3WWEVGtD2WM6oGvYeyzn/bDPWybKIThr2L3ojID7mGygn4V2D5TnWDfNCYWHG7bXPjy7XG7+roYoEZFeuCU8K92NfBMgz6t5gDIG3vc1fpT4sieW6vnygZN4ZGe3q/L0zX9Gu+QkpAm/idfObrKs93cWQ=
  - secure: mZQLxyG2fnqkXfYf1T7gX918jpWA9g+8cW20lFXiLYhMwUuqhiAV0N8698o+LLSkjmIpjn1aVQqZEDPkGdf1qlzvH0eipmygLESuySRlsUqEg3wlOVnuQJIGqcDCtdK9jWBuCMgVBAdq/eGJ7sXkt941IHMZMSfkEbMEEx/YCn1EoGqxuk3Y5OFsabz4FersUZ8RFVPwODgSX3dRNZkWo8uwx8bsbhBT9RMoTx4GVn+QXYCl8P+fXXfV1Mtj+284pt1jXyqxdxMdnIZGw2ct5SY9WUmO9Yr9nlyM5n9qoBtulK4QKX/3TL7F5UO/s3TWE6Wswe8cc/+oOgFwVHUNe9etEbCT2B/llyZQfEgWeitNSvBKfzVKmZi6i8R8ds9GsP9Xcj0sA3zHMtcl/t0jdhFp8NLrLn9hPghooMblMExREkuSC6n5/ZGay4UJBbDU717ezWmRk21SP/zBXK3oOiPTVPmEMHsi6kpMt/9CuF7FOXeLeG6faA3NXzpgIIKTzhe868/ZdXi6B5uQdrui2q10LIDyMBzciUeSATeWXTAVXjdRgLGcxZwogSBtG032GOMebJgzOdN/Yl2/1Ncqa8M2j1AP/6Pp8DyIhIs1kQiWYp4lnpPQgjRbEUR5KoOYA3ZHozvN+DtoHF1x4lb5lrMs4lvYaEqXme33ktWZfm4=
jobs:
  include:
    - name: Kylo Ren
    - name: Rey
    - name: Luke Skywalker
    - name: Obi-Wan Kenobi
    - name: Darth Plagueis
notifications:
  slack:
    rooms:
      secure: QumU9uLvDaMUznlXwruxSe9l0rOQqchBAxxYuFaufkrtAbqoPNljJlQYqZaw4PPxeom1rMv/rapYUTEIdzStuJ+LtYH4zjcM8hvSCZJPIK1W1GmnOCOlFBau19dXZcVXlVQxLr4q90/Yj9bJOsG8mFSeSr+i+YgR4QNBZIM3XcfNZTJlZ9uEHHXdC2MhGPwCJQ+9QnBqZ0CfjJSOyq76armHrOgt9sviyUSzV9+GDqUGomMyfsJodK33aB1aaLW2REL3KUXTcBgYbS34k05TMQVv4lZ5Li731IdmzClyT2I/MEsotzg/b4SNM5V+MO9l5mrtscWEdEcIY/n/E365o8c1qtwcWhPKW807+32tOCOakryeXkm8Hjiv0s+Wn12CDWwHQN5vrRHUpR1xndRkZRr/SePgHoGnF5qDvU085ANjr40Pgd+Bsg3bZgM8nAEWENQ6ZlsN8KNM3Xqgw5S/LI2DlF7u3MkBmdVw2lZBAT6096q/Wn9qcAsJilBK9UKRKknvZ5nzwITzBwfR/PDBnV6clX53G3K0YQ1+iM2QjaWibpW8HlVMREO6b1axb2bt0SpAX5b/tZAUYmX17LPhXnyrOGp1nC+rrVAgzxa8uLtzUxg2b6XvdtJYQH4KJpV5V5pZOi+n//nzY5LEMF90a+RHbvVxoMh93yX+2rr3L9M=
    template:
      - "*%{branch}* (test <%{build_url}|#%{build_number}>) %{result} in %{duration}. <https://dashboard.cypress.io/#/projects/4opx2c/runs|View Runs>."
before_install:
- npm --version
- npm config set python /usr/bin/python2.7
install:
- source config.sh
- npm ci
- $(npm bin)/cypress install
- git clone $FOURFRONT_REPO ./fourfront
- |
  if [ $FOURFRONT_BRANCH != "master" ]; then
    cd ./fourfront
    git fetch origin $FOURFRONT_BRANCH
    git checkout $FOURFRONT_BRANCH
    echo "Checked out branch $FOURFRONT_BRANCH" 
    cd ..
  fi
script:
- |
  travis_wait 59 $(npm bin)/cypress run --record --key $CYPRESS_KEY \
  --project ./fourfront/deploy/post_deploy_testing \
  --browser chrome \
  --env Auth0Client=$Auth0Client,Auth0Secret=$Auth0Secret \
  --config baseUrl=$CYPRESS_BASE_URL \
  --parallel
after_script:
- echo $BUILD_AGGREGATE_STATUS
after_success:
- echo $TRAVIS_COMMIT_MESSAGE
- MSG_NO_WHITESPACE="$(echo -e "${TRAVIS_COMMIT_MSG}" | tr -d '[:space:]')"
- echo $MSG_NO_WHITESPACE
- echo $TRAVIS_PULL_REQUEST
- echo $TRAVIS_BRANCH
after_failure:
- export $(cat .to_export_back) >> /dev/null
