language: node_js
sudo: true
if: tag IS blank
node_js:
  - 10
cache:
  npm: true
  directories:
  - "~/.cache"
addons:
  apt:
    packages:
    - bsdtar
    - build-essential
    - make
    - libgconf-2-4
env:
  global:
  - USER="4dn-dcic"
  - secure: fJT/nDt68Av0IsbwDk9z/qk36uwv81Y27u81I4MaeAMUsMiQMSXd2NaBmvqD+/utf0toAxi7f0vadHchG2dGfR0ZlbVVMTx9xeG7ahMILHH2m/g9k2yI2HnFl2eBryckfnGwtLuLDxYCY2qwkSP6WCw4Hy3yNVd5zWUMabf7/t92IoMezjbdwn/iwQqzyvU6PESgiWjAjuAHjsQQHWIJoIpsB9PM+R1uRIdIf7dV6tytKd5cCUloHJolniJpJtQM4jsTOBlWWaYlzDbRivIhmxqSwL+mBG8VsBkk9f8AFRdvJ3d6M+Kp67IxQ8Cyy+Efavs3K7Lc0eZD98tWz0Hta++Cm5C5dCKcgSZMF4ift+dEkXei/YUTO3ruBV/Ogd7Nxv6vLoFmL5v+FsVj3+TTnUvjwKcPjF81rRP7tldi+AXipG7M7CVKUdPbTuQY+hMZM/i7RgDsAWCFKwgOvKECYLeGFhE+1YPgKXVcuOkf0y++k/HB0rP8pD/94cyA5dUW85vNXh/c0iSF3m77X2D16RZCi3UaCX5okrInNn/MzPzirRNkVAGsmUgFgJvi97mlAUkzMyWhsx+1+bJlMSmN/+AZ/u613SVHuV19xdFa38zsQ/xfegZQuueoBOFd5amEghjkRTYIbPLJ/IeOvRM0ayekjQAtEdP3Na5Hw2sxj5Q=
  - secure: ES6kTjktJy60LkwMGBhMs5ueoF+v7txcTIE5UmcED9Jg2KjVDgMoEsKYPk6jaUCFrwe3KAdReAyUBN+o0oOAQN03wkoTHiUKcK6dSSgtE8Z3GXERyDHdf4AJHgj7fRl59QBmLBwc0b+21zJofb9t1va31bm8baulcxsbWqkzulWtqyBuFtoa6GAwXcP7XzZE45zoMfQPtH2HvESC67cXxOQFnNSCx040HaK5qqvBYkRIN7Ee8skrN+ZK0gurb3zpZz9DURlQ4O7OoGi5QN1ejXAbSKWj0L8luPT31S8cFlb7yZYYQIlnSwpJP760V0MrQ2ZmbGJ0n5SIUpOdjilyPsNFW3eNFf42g4KcV5stg8GQ5hg7Dv3RuH4cpYM6dS1rrDOk05wE/BF2hlSLf8X8RGGFTLyX8cpWaNvL9KK/qDYqzbzVjCitsC+KEL9xIOSD6bf7R5xPCz55eyVp4YbkP+xtAHFMIUku+D1kfIBajwiSlHioowOVMaJ9J8rT6y4liVNMT8LSZHwB1soNnceIUbO97gfh7vONwYNc+LhIU132ftsqoM1Utj1wp21yEIGUZUAmvglbv5m7IYUB5XEyV6WSHSHAICrDgOG6Lbv1DuT6oeGavqfjFx+LklXPDR55Ye/n7KPsfjUZJxp2uw6WjGuLPJVuNVP0kwKx6koqvTk=
  - secure: f33pvCgWPnoeX6BT6iJbJ8rIucz89Z5UImhqpL8Np1O9QbZduYiZ7wWzX9HfIXlD8Rq4kAHb1Yiwh7RmVJH6AFXiimjBLWP6Rr/XBvuChB3bLfIvurlVppDAa4vZ8jzO9gezZ+9GnWaRq1TcAGnvymtZW78f/DiWhOzeslXUfmkwTshZ+SgHtia8Ml3B7sKSLIFxXQ/ZOYMzvrF7w5FqFmSi5Mp+vKLnXIEa0LuLx+Vh+Q4kXzr2pkWejwMPzCOeXQ1bnddCpME2Qa5D4tW8PkK/iikPRn+WN7+VHAn10Za32wFH3cfCYFIq6wkSgTF6sPAJLy1u2l+Zj/E8F2LLmexHufGCkDskFaYbem6IKfA6ELZfQHgdGiDU4oD9175JNvHPUjzJHt3+EgEgmke+NOjAn31Qb1uD1fHemH2l/kCGKyz48d89biIhw1v7oCuojGgohEqA2tMvsaIpIrMBlez+yQrt2RzWE4Qazpbc15a54I5vGWYcvmO95ybdGj4DJDun4a46QEDmb5YkbSEiiCUwNnTjfZggm1yL3MfdAFBfA3kqaUt0jbv09secRl8ILkkNX1Ld7u1T0n69dBpgHHiGIO7g8aSToe6V3Zr7ZEA8LY4uAReV7ARGn5p4NN7Sl2lWuHZ/G/d328/eS7We4oYx+hw0JHJOjWfGp32N+1o=
notifications:
  slack:
    rooms:
      secure: QumU9uLvDaMUznlXwruxSe9l0rOQqchBAxxYuFaufkrtAbqoPNljJlQYqZaw4PPxeom1rMv/rapYUTEIdzStuJ+LtYH4zjcM8hvSCZJPIK1W1GmnOCOlFBau19dXZcVXlVQxLr4q90/Yj9bJOsG8mFSeSr+i+YgR4QNBZIM3XcfNZTJlZ9uEHHXdC2MhGPwCJQ+9QnBqZ0CfjJSOyq76armHrOgt9sviyUSzV9+GDqUGomMyfsJodK33aB1aaLW2REL3KUXTcBgYbS34k05TMQVv4lZ5Li731IdmzClyT2I/MEsotzg/b4SNM5V+MO9l5mrtscWEdEcIY/n/E365o8c1qtwcWhPKW807+32tOCOakryeXkm8Hjiv0s+Wn12CDWwHQN5vrRHUpR1xndRkZRr/SePgHoGnF5qDvU085ANjr40Pgd+Bsg3bZgM8nAEWENQ6ZlsN8KNM3Xqgw5S/LI2DlF7u3MkBmdVw2lZBAT6096q/Wn9qcAsJilBK9UKRKknvZ5nzwITzBwfR/PDBnV6clX53G3K0YQ1+iM2QjaWibpW8HlVMREO6b1axb2bt0SpAX5b/tZAUYmX17LPhXnyrOGp1nC+rrVAgzxa8uLtzUxg2b6XvdtJYQH4KJpV5V5pZOi+n//nzY5LEMF90a+RHbvVxoMh93yX+2rr3L9M=
    template:
      - "*%{branch}* (test <%{build_url}|#%{build_number}>) %{result} in %{duration}. <https://dashboard.cypress.io/#/projects/4opx2c/runs|View Runs>."
before_install:
- npm --version
- npm config set python /usr/bin/python2.7
- 
install:
- source config.sh
- npm install --update
- $(npm bin)/cypress install
- git clone $FOURFRONT_REPO ./fourfront
- |
  if [ $FOURFRONT_BRANCH != "master" ]; then
    cd ./fourfront
    git fetch origin $FOURFRONT_BRANCH
    git checkout $FOURFRONT_BRANCH
    echo "Checked out branch $FOURFRONT_BRANCH" 
    cd ..
  fi
script:
- |
  travis_wait 40 $(npm bin)/cypress run --record --key $CYPRESS_KEY \
  --project ./fourfront/deploy/post_deploy_testing \
  --env Auth0Client=$Auth0Client,Auth0Secret=$Auth0Secret \
  --config baseUrl=$CYPRESS_BASE_URL
after_script:
- echo $BUILD_AGGREGATE_STATUS
after_success:
- echo $TRAVIS_COMMIT_MESSAGE
- MSG_NO_WHITESPACE="$(echo -e "${TRAVIS_COMMIT_MSG}" | tr -d '[:space:]')"
- echo $MSG_NO_WHITESPACE
- echo $TRAVIS_PULL_REQUEST
- echo $TRAVIS_BRANCH
after_failure:
- export $(cat .to_export_back) >> /dev/null